### ISSUE TITLE
Re-install Sentry once fixed for RPI

### ISSUE THREAD

**Issue by bengineer19** [bengineer19/vst4free-frontend#11]
Pending resolution of [this issue](https://github.com/getsentry/sentry-cli/issues/591)

**Comment by developius** [comment]
Did you want to use the sentry CLI for reporting bugs during SSG?

**Comment by bengineer19** [comment]
This issue tracker is actually out of date now, I moved to GitLab :P This repo mirrors GitLab tho.
I'm now using Sentry again so it's all gooood

**Comment by developius** [comment]
Yay for sentry
